# Generated by Django 5.2.6 on 2026-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='badges',
            field=models.CharField(default='New Donor', max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='donation_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
